# Generated by Django 3.2.5 on 2021-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210810_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catgory',
            field=models.IntegerField(choices=[(1, 'ข่าวประกาศ'), (2, 'โฆษณา'), (3, 'บันทึก')], default=1),
        ),
    ]
