# Generated by Django 3.2.5 on 2021-08-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_author_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='catgory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_cteated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='titie',
            new_name='title',
        ),
    ]
